// //shows an alert when the page opens
// alert("javascript page has been successfully loaded");

// write to the inspector console
console.log("this is a console message");

// convert DOMContentLoaded(usually generated by AI) to window.onload
window.onload = async () => {
  console.log("window has loaded");

  // retrives a specific element using the id from the html page
  // 'elemenT': singular element, not plural
  document.getElementById("important");

  //amnipulate the text of the selected element
  document.getElementById("important").innerHTML = "i have changed the text with js";

  //store long document text into a variable
  let importantParagraph = document.getElementById("important");
  importantParagraph.style.backgroundColor = "salmon";
  importantParagraph.classList.add("hide");
  importantParagraph.classList.remove("hide");

  // adding elements to html using js
  // 4 steps
  // 1. getting the element that we will add a child to
  let c = document.getElementById("container");
  // 2. what type of tag we will create
  let i = document.createElement("img");
  // 3. modify new element as needed
  i.src =
    "https://images.squarespace-cdn.com/content/v1/607f89e638219e13eee71b1e/1684821560422-SD5V37BAG28BURTLIXUQ/michael-sum-LEpfefQf4rU-unsplash.jpg";
  //4. add the new. hild to the parent
  c.appendChild(i);

  // add an event listener to the parent div
  c.addEventListener("click", () => {
    console.log("clicked");

    if (importantParagraph.classList.contains("hide")) {
      importantParagraph.classList.remove("hide");
    } else {
      importantParagraph.classList.add("hide");
    }
  });

  // use class as the selector for the elements(plural)
  // think about structuring the data -- there are multiple ways to modify && find the most suitable one
  let blues = document.getElementsByClassName("blue");
  blues[0].style.backgroundColor = "skyblue";

  for (let b of blues) {
    b.style.border = "navy solid 4px";
  }

  // making an api request
  // 1. create url params(everything that goes after the ?)
  let params = new URLSearchParams({
    apikey: API_KEY,
    s: "Beetlejuice",
    type: "movie",
  });

  //2. create the url
  let url = "https://www.omdbapi.com/?" + params.toString();

  //3. make the request to the url using fetch
  let response = await fetch(url);
  console.log(response);

  let movieData = await response.json();
  console.log(movieData);
  let movies = movieData.Search;
  console.log(movies);

  //4. manipulate the page with the data
  //dynamically adding to my webpage using the data given to me from the api
  for (let m of movies) {
    let div = document.createElement("div");
    div.textContent = m.Title;
    let poster = document.createElement("img");
    poster.src = m.Poster;

    c.appendChild(poster);
    c.appendChild(div);
  }
};
